export const MAX_DAILY_CREDITS_FREE = 500;
export const MAX_DAILY_CREDITS_PREMIUM = 5000;

export const AI_COST = {
  LITE: 1,
  STANDARD: 2,
  GROUNDING_SEARCH: 5,
  GROUNDING_MAPS: 10,
  HEAVY_REASONING: 15,
  IMAGE_ANALYSIS: 8
};

